import { Router, type IRouter } from "express";
import profilesRouter from "./profiles";
import organizationsRouter from "./organizations";
import trucksRouter from "./trucks";
import requestsRouter from "./requests";
import bidsRouter from "./bids";
import jobsRouter from "./jobs";
import dashboardRouter from "./dashboard";
import walletRouter from "./wallet";
import accountRouter from "./account";
import dumpSitesRouter from "./dump-sites";
import binOrdersRouter from "./bin-orders";
import projectsRouter from "./projects";
import factoringRouter from "./factoring";
import quickbooksRouter from "./quickbooks";
import evidenceRouter from "./evidence";
import driverEventsRouter from "./driver-events";
import ticketsRouter from "./tickets";
import storageRouter from "./storage";
import driverDocsRouter from "./driver-docs";
import payoutsRouter from "./payouts";
import messagesRouter from "./messages";
import staffAuthRouter from "./staff-auth";
import adminRouter from "./admin";
import ratingsRouter from "./ratings";
import mapRouter from "./map";
import trackingRouter from "./tracking";
import copilotRouter from "./copilot";
import notificationsRouter from "./notifications";
import recurringHaulsRouter from "./recurring-hauls";

const router: IRouter = Router();

router.use(profilesRouter);
router.use(organizationsRouter);
router.use(trucksRouter);
router.use(requestsRouter);
router.use(bidsRouter);
router.use(jobsRouter);
router.use(dashboardRouter);
router.use(walletRouter);
router.use(accountRouter);
router.use(dumpSitesRouter);
router.use(binOrdersRouter);
router.use(projectsRouter);
router.use(factoringRouter);
router.use(quickbooksRouter);
router.use(evidenceRouter);
router.use(driverEventsRouter);
router.use(ticketsRouter);
router.use(storageRouter);
router.use(driverDocsRouter);
router.use(payoutsRouter);
router.use(messagesRouter);
router.use(staffAuthRouter);
router.use(adminRouter);
router.use(ratingsRouter);
router.use(mapRouter);
router.use(trackingRouter);
router.use(copilotRouter);
router.use(notificationsRouter);
router.use(recurringHaulsRouter);

export default router;
