/** Semantic color palette — replace values when the design system is finalized. */
export const colors = {
  light: {
    background: "#f9f9f9",
    foreground: "#0f172a",
    card: "#ffffff",
    cardForeground: "#0f172a",
    popover: "#ffffff",
    popoverForeground: "#0f172a",
    primary: "#FF6A00",
    primaryForeground: "#0f172a",
    secondary: "#1c2333",
    secondaryForeground: "#f9f9f9",
    muted: "#f0f4f8",
    mutedForeground: "#64748b",
    accent: "#FF6A00",
    accentForeground: "#0f172a",
    destructive: "#ef4444",
    destructiveForeground: "#ffffff",
    border: "#dde4ed",
    input: "#dde4ed",
    ring: "#FF6A00",
    sidebar: "#ffffff",
    sidebarForeground: "#0f172a",
    sidebarBorder: "#dde4ed",
    sidebarPrimary: "#FF6A00",
    sidebarPrimaryForeground: "#0f172a",
    sidebarAccent: "#f0f4f8",
    sidebarAccentForeground: "#0f172a",
  },
  dark: {
    background: "#0A0A0C",
    foreground: "#f0f6ff",
    card: "#141416",
    cardForeground: "#f0f6ff",
    popover: "#141416",
    popoverForeground: "#f0f6ff",
    primary: "#FF6A00",
    primaryForeground: "#0f172a",
    secondary: "#1E1E22",
    secondaryForeground: "#f0f6ff",
    muted: "#1A1A1E",
    mutedForeground: "#8ba0b8",
    accent: "#FF6A00",
    accentForeground: "#0f172a",
    destructive: "#b91c1c",
    destructiveForeground: "#f0f6ff",
    border: "#262629",
    input: "#262629",
    ring: "#FF6A00",
    sidebar: "#0A0A0C",
    sidebarForeground: "#f0f6ff",
    sidebarBorder: "#262629",
    sidebarPrimary: "#FF6A00",
    sidebarPrimaryForeground: "#0f172a",
    sidebarAccent: "#1A1A1E",
    sidebarAccentForeground: "#f0f6ff",
  },
} as const;

export type ColorScheme = keyof typeof colors;
export type ColorToken = keyof (typeof colors)["light"];
